title: anfvelasquezpe.github.io
description: Analítica - Ciencia de datos aplicada
template:
  repo: anfvelasquezpe.github.io-template
  name: anfvelasquezpe.github.io
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
